const data = [
    {
    "Headline": "Leading Chip Stock ASML Remains In Buy Zone Amid Hot Growth",
    "ArticleContent": "Dutch company ASML (ASML) is a strong candidate for investment in the top-performing semiconductor sector. The chip stock is the current leader of IBD's hot Semiconductor Equipment group, which ranks 13th out of 197 industries. After breaking out of a cup base and passing a 683.18 buy point on May 18, ASML has traded in a tight range. It remains in a buy zone that goes to 717.34. That low-volatility stretch has also created a ",
    "Source": null,
    "PublicationDate": "2023-06-09T16:38:53",
    "UpdateDate": "0001-01-01T00:00:00",
    "Symbols": "ASML",
    "Author": "JUAN CARLOS ARANCIBIA",
    "Publisher": "",
    "Articleurl": "https://www.investors.com/stock-lists/ibd-sector-leaders/chip-stock-asml-remains-in-buy-zone-amid-hot-growth/",
    "ImageUrl": "https://www.investors.com/wp-content/uploads/2023/01/Stock-ASML-containerslots-01-company.jpg",
    "Image150Url": "https://www.investors.com/wp-content/uploads/2023/01/Stock-ASML-containerslots-01-company-150x150.jpg",
    "Category": "IBD Sector Leaders"
    },
    {
    "Headline": "Tech Stocks Lead Stock Market Rally; Jobless Claims Highest Since October 2021",
    "ArticleContent": "The tech-heavy Nasdaq composite bounced sharply Thursday, leading the stock market higher, as first-time jobless claims hit their highest level since October 2021. The stock market uptrend features a number of leading stocks in or near buy zones, with a handful more this week. IBD SwingTrader idea Floor & Decor (FND) and Kinsale Capital (KNSL) are in buy zones following this week's moves. Jobless Claims, Earnings Movers The final round of initial unemployment claims before ",
    "Source": null,
    "PublicationDate": "2023-06-08T20:16:12",
    "UpdateDate": "0001-01-01T00:00:00",
    "Symbols": "GME, KNSL, FND, ASML, UBER",
    "Author": "SCOTT LEHTONEN",
    "Publisher": "",
    "Articleurl": "https://www.investors.com/market-trend/the-big-picture/stock-market-rally-led-by-tech-stocks-jobless-claims-highest-since-october-2021/",
    "ImageUrl": "https://www.investors.com/wp-content/uploads/2021/08/Stock-bullProfile-adobe.jpg",
    "Image150Url": "https://www.investors.com/wp-content/uploads/2021/08/Stock-bullProfile-adobe-150x150.jpg",
    "Category": "The Big Picture"
    },
    {
    "Headline": "Building Better Breakouts: These Growth Stocks Are Getting Pumped",
    "ArticleContent": "The latest IBD/TIPP survey shows the U.S. economy remains stuck in a rut, and President Joe Biden's job approval rating just slid to its worst level of 2023. Yet, the IBD Breakout Stocks Index features top-rated growth names like Celsius (CELH), Aehr Test Systems (AEHR), Taiwan Semiconductor (TSM) and many others focused on fielding or fortifying a crop of fresh breakouts. The market indexes continue to show strength and resilience in the face of inflation ",
    "Source": null,
    "PublicationDate": "2023-06-07T19:12:51",
    "UpdateDate": "0001-01-01T00:00:00",
    "Symbols": "ASML, TSM, CSCO, SHOP, CELH",
    "Author": "MATTHEW GALGANI",
    "Publisher": "",
    "Articleurl": "https://www.investors.com/research/breakout-stocks/growth-stocks-to-watch-asml-tsm-stock-among-top-names-pumping-up-breakouts/",
    "ImageUrl": "https://www.investors.com/wp-content/uploads/2023/06/Stock-muscles-adobe.jpg",
    "Image150Url": "https://www.investors.com/wp-content/uploads/2023/06/Stock-muscles-adobe-150x150.jpg",
    "Category": "Breakout Stocks"
    },
    {
    "Headline": "EV Boom Is Just One Growth Catalyst Sparking This Small-Cap Stock",
    "ArticleContent": "As semiconductor equipment companies ASML (ASML), Lam Research (LRCX), Entegris (ENTG), Axcelis Technologies (ACLS) and KLA (KLAC) flash new breakouts, Aehr Test Systems (AEHR) etches a move of its own. Boosted by the boom in electric vehicles, AEHR stock has burned in a spot on the IBD Breakout Stocks Index alongside ASML, LRCX, ENTG and KLAC. The chip-equipment group ranks a strong No. 10 out of the 197 groups IBD tracks. Further displaying the strength ",
    "Source": null,
    "PublicationDate": "2023-05-31T14:57:31",
    "UpdateDate": "0001-01-01T00:00:00",
    "Symbols": "AEHR, KLAC, LRCX, ASML, NVDA",
    "Author": "MATTHEW GALGANI",
    "Publisher": "",
    "Articleurl": "https://www.investors.com/research/breakout-stocks/aehr-stock-charges-ahead-on-ev-boom-data-storage-trends/",
    "ImageUrl": "https://www.investors.com/wp-content/uploads/2023/05/Stock-AIcarengineering-01-adobe.jpg",
    "Image150Url": "https://www.investors.com/wp-content/uploads/2023/05/Stock-AIcarengineering-01-adobe-150x150.jpg",
    "Category": "Breakout Stocks"
    },
    {
    "Headline": "Tech Roars Back As MSFT, ASML, AMAT, ORCL Lead Industry Charge",
    "ArticleContent": "Stock market history shows that the best stocks to buy and watch often hail from the top-ranked industry groups. As last year's bear market ravaged the tech sector, bellwether names like Microsoft (MSFT), Adobe (ADBE), Oracle (ORCL), Broadcom (AVGO), Applied Materials (AMAT) and ASML (ASML) fell out of favor. But boosted by the buzz around artificial intelligence, Nvidia (NVDA) and others, Wall Street has regenerated its interest in tech stocks. That has lifted several groups ",
    "Source": null,
    "PublicationDate": "2023-05-30T19:59:07",
    "UpdateDate": "0001-01-01T00:00:00",
    "Symbols": "AVGO, MSFT, ASML, MBLY, ADBE, ORCL, AMAT",
    "Author": "MATTHEW GALGANI",
    "Publisher": "",
    "Articleurl": "https://www.investors.com/research/best-stocks-to-watch-in-top-ranked-industry-groups/",
    "ImageUrl": "https://www.investors.com/wp-content/uploads/2023/05/Stock-robothumanhandstouch-01-adobe.jpg",
    "Image150Url": "https://www.investors.com/wp-content/uploads/2023/05/Stock-robothumanhandstouch-01-adobe-150x150.jpg",
    "Category": ""
    },
    {
    "Headline": "Dow Jones Falls On Debt-Ceiling Deal; Nvidia Surges To $1 Trillion Market Cap",
    "ArticleContent": "The Dow Jones Industrial Average fell Tuesday, while tech stocks kept running after President Biden and House Speaker Kevin McCarthy reached a deal to raise the debt ceiling over the weekend. Meanwhile, tech titan Nvidia (NVDA) surged Tuesday, hitting the $1 trillion in market capitalization for the first time. Up next, the House, which appears to be the main obstacle to the deal's passage, is expected to vote Wednesday night. The legislation's first test is ",
    "Source": null,
    "PublicationDate": "2023-05-30T13:47:23",
    "UpdateDate": "0001-01-01T00:00:00",
    "Symbols": "ANET, ASML, NVDA, TSLA, TSM",
    "Author": "SCOTT LEHTONEN",
    "Publisher": "",
    "Articleurl": "https://www.investors.com/market-trend/stock-market-today/dow-jones-futures-debt-ceiling-deal-nvidia-stock-to-hit-trillion-market-cap/",
    "ImageUrl": "https://www.investors.com/wp-content/uploads/2017/03/stock-wallstreet-031317-shutter.jpg",
    "Image150Url": "https://www.investors.com/wp-content/uploads/2017/03/stock-wallstreet-031317-shutter-150x150.jpg",
    "Category": "Stock Market Today"
    },
    {
    "Headline": "Dow Jones Futures Rise On Debt-Ceiling Buzz; Nvidia, Chip, AI Plays Soar, But Market Breadth Terrible",
    "ArticleContent": "Dow Jones futures rose modestly early Friday, along with S&P 500 futures and Nasdaq futures, amid reports that a debt-ceiling deal isn't far off. Key inflation data is on tap before the market open. Costco Wholesale (COST), Ulta Beauty (ULTA), Workday (WDAY), Deckers Outdoor (DECK) and Marvell Technology (MRVL) headlined earnings reports Thursday night. The stock market rally had a wildly divergent Thursday. The Nasdaq and especially the Nasdaq 100 surged as Nvidia (NVDA) skyrocketed ",
    "Source": null,
    "PublicationDate": "2023-05-26T11:09:14",
    "UpdateDate": "0001-01-01T00:00:00",
    "Symbols": "AMD, ANET, ASML, KLAC, MBLY, MRVL, MSFT, NVDA, WDAY",
    "Author": "ED CARSON",
    "Publisher": "",
    "Articleurl": "https://www.investors.com/market-trend/stock-market-today/dow-jones-futures-nasdaq-jumps-as-nvidia-chip-ai-plays-soar-market-breadth-terrible/",
    "ImageUrl": "https://www.investors.com/wp-content/uploads/2017/11/stock-bull-tongue-adobe.jpg",
    "Image150Url": "https://www.investors.com/wp-content/uploads/2017/11/stock-bull-tongue-adobe-150x150.jpg",
    "Category": "Stock Market Today"
    },
    {
    "Headline": "ASML Stock Surges Back Into Buy Zone On Nvidia Results, AI Angle",
    "ArticleContent": "Chip stocks have been soaring with Nvidia (NVDA) rocketing after the company trounced earnings estimates and provided what many pundits were quick to label as a guidance for the ages. The move adds to a recent fever over AI-based technologies and stocks, which provide vast potential for growth. ASML (ASML) — making the IBD Big Cap 20 list and the current leader of IBD's semiconductor equipment group — offers a great buying opportunity for those ",
    "Source": null,
    "PublicationDate": "2023-05-25T18:30:03",
    "UpdateDate": "0001-01-01T00:00:00",
    "Symbols": "ASML, NVDA",
    "Author": "STEVEN BELL",
    "Publisher": "",
    "Articleurl": "https://www.investors.com/stock-lists/ibd-big-cap-20/asml-stock-surges-back-into-buy-zone-on-nvidia-results-ai-angle/",
    "ImageUrl": "https://www.investors.com/wp-content/uploads/2021/07/Stock-ASML-hq-02-company.jpg",
    "Image150Url": "https://www.investors.com/wp-content/uploads/2021/07/Stock-ASML-hq-02-company-150x150.jpg",
    "Category": "IBD Big Cap 20"
    },
    {
    "Headline": "Screen Of The Day: These 3 Stocks Stand Out In Global Leaders List",
    "ArticleContent": "Stock screens make it easier to find winners. IBD's Screen of the Day is a go-to place for picking leaders. The Global Leaders list includes three names for further analysis. Vista Energy (VIST) is the first to note. Shares are forming a cup base with a 22.94 entry. A strong feature on the Vista chart is the multiple times the stock got support at the 50-day moving average, according to IBD MarketSmith. On the weaker ",
    "Source": null,
    "PublicationDate": "2023-05-24T18:10:54",
    "UpdateDate": "0001-01-01T00:00:00",
    "Symbols": "VIST, ASML, MNSO",
    "Author": "VIDYA RAMAKRISHNAN",
    "Publisher": "",
    "Articleurl": "https://www.investors.com/stock-lists/global-leaders/three-stocks-stand-out-in-global-leaders-list/",
    "ImageUrl": "https://www.investors.com/wp-content/uploads/2021/10/Stock-ASML-container-01-company.jpg",
    "Image150Url": "https://www.investors.com/wp-content/uploads/2021/10/Stock-ASML-container-01-company-150x150.jpg",
    "Category": "Global Leaders"
    },
    {
    "Headline": "Dow Jones Aerospace Giant Boeing Eyes Latest Buy Point. 3 Others To Buy And Watch.",
    "ArticleContent": "Among the best stocks to buy and watch, Dow Jones leader Boeing (BA), IBD Leaderboard stock ASML (ASML), IBD SwingTrader stock DraftKings (DKNG) and Cadence Design Systems (CDNS) are in or near buy zones in today's stock market action. Following recent bullish stock market gains, the market trend is in a confirmed uptrend per the IBD Big Picture. And investors should be looking for top stocks breaking out past buy points. Boeing: Dow Jones Stock ",
    "Source": null,
    "PublicationDate": "2023-05-24T13:09:05",
    "UpdateDate": "0001-01-01T00:00:00",
    "Symbols": "ASML, CDNS, DKNG, BA",
    "Author": "SCOTT LEHTONEN",
    "Publisher": "",
    "Articleurl": "https://www.investors.com/stock-lists/stocks-near-a-buy-zone/dow-jones-aerospace-giant-boeing-eyes-latest-buy-point-3-others-to-buy-and-watch/",
    "ImageUrl": "https://www.investors.com/wp-content/uploads/2016/08/stock-boeing-sign-company.jpg",
    "Image150Url": "https://www.investors.com/wp-content/uploads/2016/08/stock-boeing-sign-company-150x150.jpg",
    "Category": "Stocks Near A Buy Zone"
    }
];

export default data;