const data = {
    "ListName": "",
    "Items": [
    {
    "Symbol": "ASML",
    "CompanyName": "Asml Holding",
    "Price": 740.21,
    "PriceChange": 2.94,
    "PricePercentChange": 0.4,
    "Volume": 818000,
    "VolumePercentChange": -17.52,
    "IsIndex": null,
    "Header": "Leaders",
    "Sector": "CHIPS",
    "SectorRank": 2,
    "SymbolOrder": 0,
    "Story": "The company holds a true leadership role in the chip equipment space. With Intel, Taiwan Semiconductor and South Korean semiconductor manufacturing giants Samsung and others gearing to expand their production capacity, the Dutch expert in lithography systems stands in an enviable position. Analysts on consensus see profits growing 34% this year to $20.30 a share -- a slight revision lower -- and up another 20% in 2024.<br>",
    "UpdateDate": "6/14/2023 5:11 PM",
    "NearBuyPoint": false,
    "BuyPoint": "683.18",
    "BuyRangeFrom": "683.18",
    "BuyRangeTo": "717.34",
    "CurrentAction": "ASML is extended from a conventional buy point of 683.18. It initially joined the Leaders as it crossed a trendline. Then the large cap earned a position-size raise after surpassing its conventional buy point of 683.18. ASML previously got support near the 50-day moving average. ",
    "LeaderboardAnalysis": "This is a first stage base for ASML, a positive. The stock has made solid gains in 2023, at one point rising nearly 28%. One negative is overall institutional ownership is low, with 10% of its stock being held by funds according to MarketSmith data. Yet this could be due to the fact that ASML's principal trading market is Euronext Amsterdam. ASML is also listed on the London Stock Exchange. Plus, several funds highly rated by IBD hold stakes in the stock. <br>",
    "BackStory": "The company holds a true leadership role in the chip equipment space. With Intel, Taiwan Semiconductor and South Korean semiconductor manufacturing giants Samsung and others gearing to expand their production capacity, the Dutch expert in lithography systems stands in an enviable position. Analysts on consensus see profits growing 34% this year to $20.30 a share -- a slight revision lower -- and up another 20% in 2024.<br>",
    "IsInLeaderboard": true,
    "RecentArticle": "<div><a href=\"https://www.investors.com/stock-lists/global-leaders/three-stocks-stand-out-in-global-leaders-list/\" target=\"_blank\">IBD Screen Of The Day</a><br></div><div><a href=\"https://www.investors.com/stock-lists/ibd-big-cap-20/asml-stock-nears-new-highs-as-european-chip-giant-sets-for-big-turnaround/\" target=\"_blank\">ASML Stock Nears New Highs, Looks Set For Big Turnaround</a></div><p></p>",
    "PreviousClose": 737.27,
    "CheckupUrl": "https://research.investors.com/stock-checkup/nasdaq-asml-holding-asml.aspx",
    "LatestQtrEpsPerChg": null,
    "PriorQtrEpsPerChg": null,
    "CurQtrSalesPerChg": null,
    "CurYrEpsEstPerChg": null,
    "CompRating": null,
    "EPSRating": null,
    "RSRating": null,
    "SmrRating": null,
    "AccDisRating": null,
    "GrpStr": null,
    "ListName": "Leaders",
    "PositionSize": "Three-Quarters"
    },
    {
    "Symbol": "CELH",
    "CompanyName": "Celsius Holdings",
    "Price": 143.06,
    "PriceChange": -6.425,
    "PricePercentChange": -4.3,
    "Volume": 1754000,
    "VolumePercentChange": 47.95,
    "IsIndex": null,
    "Header": "Leaders",
    "Sector": null,
    "SectorRank": 0,
    "SymbolOrder": 0,
    "Story": "The stock moved into the S&amp;P MidCap 400 from the small-cap S&amp;P 600 on Aug. 10, 2022. Celsius is a fast-growing marketer of fat-burning beverages that contain no sugar, preservatives, aspartame or high fructose corn syrup. After registering years of losses, the Boca Raton, Fla.-based firm turned its first annual profit in 2019. Over the past four quarters, revenue growth has ranged from 117% to 192%. On Aug. 1 PepsiCo said it is investing $550 million for an estimated 8.5% ownership stake as part of a long-term distribution deal with the energy drink maker. Celsius notched a Q4 net loss of 37 cents in Q4 as revenue rose 71%. However, Celsius staged a strong profit turnaround in the first quarter of this year, earning 40 cents a share, up 344% vs. 9 cents a year ago. Q1 revenue nearly doubled to $260 million. Celsius is now seen returning to the black with a profit of $1.31 a share in 2023, with growth ramping up in 2024, up as high as 54% to $2.02.<br>",
    "UpdateDate": "6/13/2023 5:07 PM",
    "NearBuyPoint": false,
    "BuyPoint": "122.24",
    "BuyRangeFrom": "122.24",
    "BuyRangeTo": "128.35",
    "CurrentAction": "Celsius joined the Leaders from the Watchlist as it cleared a short trendline near 130. It previously fizzed out of a buy zone after reporting earnings and a healthy revenue beat, but nearly round-tripped all gains past the 122.24 entry. Now, CELH has hit the 20% profit target from 122.24. ",
    "LeaderboardAnalysis": "CELH certainly deserved time to cool off after it posted six straight weekly gains. That strong run signals demand for shares has taken over the stock. In March, CELH found support at 80, a key round number. It tested that level in October and November.<br>",
    "BackStory": "The stock moved into the S&amp;P MidCap 400 from the small-cap S&amp;P 600 on Aug. 10, 2022. Celsius is a fast-growing marketer of fat-burning beverages that contain no sugar, preservatives, aspartame or high fructose corn syrup. After registering years of losses, the Boca Raton, Fla.-based firm turned its first annual profit in 2019. Over the past four quarters, revenue growth has ranged from 117% to 192%. On Aug. 1 PepsiCo said it is investing $550 million for an estimated 8.5% ownership stake as part of a long-term distribution deal with the energy drink maker. Celsius notched a Q4 net loss of 37 cents in Q4 as revenue rose 71%. However, Celsius staged a strong profit turnaround in the first quarter of this year, earning 40 cents a share, up 344% vs. 9 cents a year ago. Q1 revenue nearly doubled to $260 million. Celsius is now seen returning to the black with a profit of $1.31 a share in 2023, with growth ramping up in 2024, up as high as 54% to $2.02.<br>",
    "IsInLeaderboard": true,
    "RecentArticle": "<p><a href=\"https://www.investors.com/news/management/leaders-and-success/celsius-ceo-embraces-wellness-in-his-brand-and-in-his-life/\" target=\"_blank\">Leaders &amp; Success: Celsius CEO Embraces Wellness</a><br><a href=\"https://www.investors.com/news/celsius-earnings-pepsico-deal-lifts-celh-stock/\" target=\"_blank\">CELH Stock Rockets On Booming North American Sales</a><br><a href=\"https://www.investors.com/news/celsius-stock-jumps-after-pepsico-announces-550-million-stake-distribution-deal/\" target=\"_blank\">Energy Drink Firm Jolts On This News With PepsiCo</a></p>",
    "PreviousClose": 149.485,
    "CheckupUrl": "https://research.investors.com/stock-checkup/nasdaq-celsius-holdings-celh.aspx",
    "LatestQtrEpsPerChg": null,
    "PriorQtrEpsPerChg": null,
    "CurQtrSalesPerChg": null,
    "CurYrEpsEstPerChg": null,
    "CompRating": null,
    "EPSRating": null,
    "RSRating": null,
    "SmrRating": null,
    "AccDisRating": null,
    "GrpStr": null,
    "ListName": "Leaders",
    "PositionSize": "Half"
    },
    {
    "Symbol": "DKNG",
    "CompanyName": "Draftkings Cl A",
    "Price": 25.27,
    "PriceChange": -0.87,
    "PricePercentChange": -3.33,
    "Volume": 9081000,
    "VolumePercentChange": -26.22,
    "IsIndex": null,
    "Header": "Leaders",
    "Sector": null,
    "SectorRank": 0,
    "SymbolOrder": 0,
    "Story": "Best known for its fantasy sports platform, DraftKings is benefiting from wider legalization of sports betting. To its credit, the stock is showing renewed signs of accumulation as it works its way higher. Operating cash flow was a negative $1.43 per share in 2022. The long-term debt to equity ratio was 95% last year. DraftKings isn't profitable yet but shows big revenue growth in recent quarters. Wall Street had expected DraftKings to lose $2.19 a share this year, but that estimate has shrunk to a loss of $1.35 a share. The net loss seen for 2024 is 35 cents as of June 13. On May 4 the company posted a Q1 adjusted loss of 51 cents per share, narrower than the previous year's loss per share of 74 cents. Analysts had expected a loss of 76 cents. Management guided for 2023 revenue of $3.14 billion to $3.24 billion, up from $2.85 billion to $3.05 billion previously. Analysts had expected $3.02 billion.<br>",
    "UpdateDate": "6/13/2023 5:44 PM",
    "NearBuyPoint": false,
    "BuyPoint": "23.75",
    "BuyRangeFrom": "23.75",
    "BuyRangeTo": "24.94",
    "CurrentAction": "DraftKings joined Leaderboard on May 18 after clearing a trendline entry near 23.75 and is now extended. Shares are in a profit zone from a standard buy point of 21.62. DKNG is building support along its fast-rising 21-day line. The stock has so far made measured pullbacks after surging out of a buy zone on Q1 results. The relative strength line recently climbed to the highest level in more than a year. ",
    "LeaderboardAnalysis": "DKNG cleared a very wide and loose cup with handle at 17.99 in February. The prior cup-with-handle base started in August and showed a pullback of 50% from peak to trough, which made it a flawed pattern. The latest cup shows a much more reasonable 21% correction from head to toe. This indicates sellers have wielded less power.<br>",
    "BackStory": "Best known for its fantasy sports platform, DraftKings is benefiting from wider legalization of sports betting. To its credit, the stock is showing renewed signs of accumulation as it works its way higher. Operating cash flow was a negative $1.43 per share in 2022. The long-term debt to equity ratio was 95% last year. DraftKings isn't profitable yet but shows big revenue growth in recent quarters. Wall Street had expected DraftKings to lose $2.19 a share this year, but that estimate has shrunk to a loss of $1.35 a share. The net loss seen for 2024 is 35 cents as of June 13. On May 4 the company posted a Q1 adjusted loss of 51 cents per share, narrower than the previous year's loss per share of 74 cents. Analysts had expected a loss of 76 cents. Management guided for 2023 revenue of $3.14 billion to $3.24 billion, up from $2.85 billion to $3.05 billion previously. Analysts had expected $3.02 billion.<br>",
    "IsInLeaderboard": true,
    "RecentArticle": "<p><a href=\"https://www.investors.com/research/draftkings-dkng-stock-buy-now/\" target=\"_blank\">Is DraftKings Stock A Buy Now?</a><br><a href=\"https://www.barrons.com/articles/draftkings-earnings-stock-price-ff852cbb?mod=bar_ibd_news\" target=\"_blank\">Barron's: What Wall Street Is Saying About DraftKings' Earnings</a></p>",
    "PreviousClose": 26.14,
    "CheckupUrl": "https://research.investors.com/stock-checkup/nasdaq-draftkings-cl-a-dkng.aspx",
    "LatestQtrEpsPerChg": null,
    "PriorQtrEpsPerChg": null,
    "CurQtrSalesPerChg": null,
    "CurYrEpsEstPerChg": null,
    "CompRating": null,
    "EPSRating": null,
    "RSRating": null,
    "SmrRating": null,
    "AccDisRating": null,
    "GrpStr": null,
    "ListName": "Leaders",
    "PositionSize": "Half"
    },
    {
    "Symbol": "DT",
    "CompanyName": "Dynatrace",
    "Price": 51.82,
    "PriceChange": 0.25,
    "PricePercentChange": 0.48,
    "Volume": 2739000,
    "VolumePercentChange": -9.1,
    "IsIndex": null,
    "Header": "Leaders",
    "Sector": "SOFTWARE",
    "SectorRank": 7,
    "SymbolOrder": 0,
    "Story": "Dynatrace, based in Waltham, Mass., makes software that provides an all-in-one intelligence platform to assist technology and digital business teams. The software updates and automates IT operations to help develop and release software faster. Few tech firms can boast double-digit profit growth in both 2022 and 2023; for Dynatrace, Wall Street expected profits to rise 29% to 88 cents a share in the fiscal year ending in March 2023; Dynatrace earned 97 cents. Analysts see the bottom line up 3% to $1 a share in FY 2024 and accelerating 17% in FY 2025. Sales have risen sharply and consistently while mutual fund ownership has climbed the past two quarters. On May 17 it reported adjusted profit of 31 cents a share, up 82% from a year ago. Revenue increased 25% to $314.5 million. Dynatrace also bumped up its revenue guidance for the current quarter and full year.",
    "UpdateDate": "6/8/2023 4:09 PM",
    "NearBuyPoint": false,
    "BuyPoint": "48.00",
    "BuyRangeFrom": "48.00",
    "BuyRangeTo": "50.40",
    "CurrentAction": "Dynatrace is just above a buy zone after initially joining Leaderboard as an earnings option trade ahead of its May 17 earnings report. Then DT shifted to the Leaders main list with an exercise of the call option that expired May 26. The 47 strike-price call was reasonably priced with a midpoint of around $1.70 at the time of its entry in Leaderboard. That equates to roughly a 3.6% risk in comparison with outright buying the stock at a per-share price near 47. ",
    "LeaderboardAnalysis": "Like the prior flat base that engendered a brief breakout and rally, \r\nthe latest consolidation is highly unusual in that it's embedded deep \r\nwithin a cavernous base. After DT peaked in October 2021 at 80.13, the stock collapsed. A 63% decline ensued, and it's taken months for Dynatrace to bottom out. The RS line is strong. The stock still has a long ways to go before challenging its all-time peak of 80.13.<br>",
    "BackStory": "Dynatrace, based in Waltham, Mass., makes software that provides an all-in-one intelligence platform to assist technology and digital business teams. The software updates and automates IT operations to help develop and release software faster. Few tech firms can boast double-digit profit growth in both 2022 and 2023; for Dynatrace, Wall Street expected profits to rise 29% to 88 cents a share in the fiscal year ending in March 2023; Dynatrace earned 97 cents. Analysts see the bottom line up 3% to $1 a share in FY 2024 and accelerating 17% in FY 2025. Sales have risen sharply and consistently while mutual fund ownership has climbed the past two quarters. On May 17 it reported adjusted profit of 31 cents a share, up 82% from a year ago. Revenue increased 25% to $314.5 million. Dynatrace also bumped up its revenue guidance for the current quarter and full year.",
    "IsInLeaderboard": true,
    "RecentArticle": "<p><a href=\"https://www.investors.com/news/technology/dt-stock-dynatrace-earnings-dynatrace-stock-q42023/\" target=\"_blank\">Dynatrace Signals Breakout On Earnings, Guidance<br></a><a href=\"https://www.investors.com/news/technology/dynatrace-stock-dynatrace-earnings-dt-stock-q42022/\" target=\"_blank\">Fiscal Q3 Results At Dynatrace Delight</a></p>",
    "PreviousClose": 51.57,
    "CheckupUrl": "https://research.investors.com/stock-checkup/nyse-dynatrace-dt.aspx",
    "LatestQtrEpsPerChg": null,
    "PriorQtrEpsPerChg": null,
    "CurQtrSalesPerChg": null,
    "CurYrEpsEstPerChg": null,
    "CompRating": null,
    "EPSRating": null,
    "RSRating": null,
    "SmrRating": null,
    "AccDisRating": null,
    "GrpStr": null,
    "ListName": "Leaders",
    "PositionSize": "Half"
    },
    {
    "Symbol": "HUBS",
    "CompanyName": "Hubspot",
    "Price": 503.94,
    "PriceChange": -8.73,
    "PricePercentChange": -1.7,
    "Volume": 597000,
    "VolumePercentChange": -1.95,
    "IsIndex": null,
    "Header": "Leaders",
    "Sector": null,
    "SectorRank": 0,
    "SymbolOrder": 0,
    "Story": "The Cambridge, Mass., firm specializes in helping businesses automate marketing and sales operations. Its cloud-based platform also assists clients in social media, search engine optimization and website content management. Earnings and sales have grown sharply over most of the past eight quarters. Q1 profit growth accelerated for the third straight quarter, up 122%. Revenue increased 27% to $501.6 million. Analysts surveyed by FactSet have bumped up their consensus forecast, now seeing a 66% jump in earnings this year to $4.84 a share. At least eight members of the IBD Mutual Fund Index own shares.<br>",
    "UpdateDate": "6/13/2023 5:43 PM",
    "NearBuyPoint": false,
    "BuyPoint": "431.60",
    "BuyRangeFrom": "431.60",
    "BuyRangeTo": "453.18",
    "CurrentAction": "HubSpot recovered off lows Tuesday after finding support at the 21-day exponential moving average. It joined Leaderboard as a half-size position after it popped sharply on excellent earnings and gave bullish guidance. It is now well extended from conventional entries at 418.39 and at 431.60, hitting the 20% profit goal for each. An earnings gap justified an alternate entry near 455.68. ",
    "LeaderboardAnalysis": "HubSpot fell sharply during the 2022 tech washout. So, overhead supply remains a concern. Yet this is also an early-stage breakout. The stock has made a strong rebound since October and logged numerous days of gains in heavy volume. Headed into the Q1 report, HUBS was trading tightly near the buy point while holding above its 10-week moving average.<br>",
    "BackStory": "The Cambridge, Mass., firm specializes in helping businesses automate marketing and sales operations. Its cloud-based platform also assists clients in social media, search engine optimization and website content management. Earnings and sales have grown sharply over most of the past eight quarters. Q1 profit growth accelerated for the third straight quarter, up 122%. Revenue increased 27% to $501.6 million. Analysts surveyed by FactSet have bumped up their consensus forecast, now seeing a 66% jump in earnings this year to $4.84 a share. At least eight members of the IBD Mutual Fund Index own shares.<br>",
    "IsInLeaderboard": true,
    "RecentArticle": "<p><a href=\"https://www.investors.com/news/technology/hubs-stock-hubspot-earnings-q12023/\" target=\"_blank\">HubSpot Earnings Top Expectations; CEO Touts AI Roadmap<br></a><a href=\"https://www.investors.com/research/the-new-america/hubs-stock-how-hubspot-expanded-marketing-customer-management-payment-services/\" target=\"_blank\">How HubSpot Expanded From Marketing, To Customer Management And Payments</a><br></p>",
    "PreviousClose": 512.67,
    "CheckupUrl": "https://research.investors.com/stock-checkup/nyse-hubspot-hubs.aspx",
    "LatestQtrEpsPerChg": null,
    "PriorQtrEpsPerChg": null,
    "CurQtrSalesPerChg": null,
    "CurYrEpsEstPerChg": null,
    "CompRating": null,
    "EPSRating": null,
    "RSRating": null,
    "SmrRating": null,
    "AccDisRating": null,
    "GrpStr": null,
    "ListName": "Leaders",
    "PositionSize": "Half"
    },
    {
    "Symbol": "META",
    "CompanyName": "Meta Platforms",
    "Price": 273.35,
    "PriceChange": 2.03,
    "PricePercentChange": 0.75,
    "Volume": 18210000,
    "VolumePercentChange": -18.41,
    "IsIndex": null,
    "Header": "Leaders",
    "Sector": null,
    "SectorRank": 0,
    "SymbolOrder": 0,
    "Story": "The social network is a turnaround story amid declining earnings and revenue. But after another announcement of new job cuts, annual earnings estimates have improved yet again. Wall Street has sharply hoisted the company's profit estimates recently and see profit up 95% this year to $16.73 a share. A prior forecast saw a 45% rise, which in turn was way up from an earlier jump of 12%. On April 26 the firm posted EPS of $2.20 and revenue of $28.65 billion, both above Wall Street views. Daily active users were slightly above expectations while monthly active users were in line. In Q2, the firm expects revenue of between $29.5 billion and $32 billion. The midpoint was well clear of analyst views for $29.5 billion.<br>",
    "UpdateDate": "6/9/2023 4:15 PM",
    "NearBuyPoint": false,
    "BuyPoint": "197.16",
    "BuyRangeFrom": "197.16",
    "BuyRangeTo": "207.02",
    "CurrentAction": "Meta Platforms surged after reporting earnings and hit the 20% profit goal from a flat-base entry. It is now moving higher again after a pause. META previously moved above a trendline on March 14. The relative strength line is still near highs. ",
    "LeaderboardAnalysis": "The flat base formed as the stock held support at the 21-day exponential moving average. A short trendline drawn within the base produced an early entry near 190-192.<br>",
    "BackStory": "The social network is a turnaround story amid declining earnings and revenue. But after another announcement of new job cuts, annual earnings estimates have improved yet again. Wall Street has sharply hoisted the company's profit estimates recently and see profit up 95% this year to $16.73 a share. A prior forecast saw a 45% rise, which in turn was way up from an earlier jump of 12%. On April 26 the firm posted EPS of $2.20 and revenue of $28.65 billion, both above Wall Street views. Daily active users were slightly above expectations while monthly active users were in line. In Q2, the firm expects revenue of between $29.5 billion and $32 billion. The midpoint was well clear of analyst views for $29.5 billion.<br>",
    "IsInLeaderboard": true,
    "RecentArticle": "<div><a href=\"https://www.investors.com/news/technology/meta-stock-meta-earnings-q1-2023/\" target=\"_blank\">Meta Soars As Facebook Parent Blows Past Earnings Forecasts</a> <br></div><div><a href=\"https://www.investors.com/research/ibd-stock-of-the-day/meta-stock-gets-boost-from-layoffs-efficiency/\" target=\"_blank\">Meta, IBD Stock Of The Day, Aims For 'Year Of Efficiency' In A Tough Time</a></div>",
    "PreviousClose": 271.32,
    "CheckupUrl": "https://research.investors.com/stock-checkup/nasdaq-meta-platforms-meta.aspx",
    "LatestQtrEpsPerChg": null,
    "PriorQtrEpsPerChg": null,
    "CurQtrSalesPerChg": null,
    "CurYrEpsEstPerChg": null,
    "CompRating": null,
    "EPSRating": null,
    "RSRating": null,
    "SmrRating": null,
    "AccDisRating": null,
    "GrpStr": null,
    "ListName": "Leaders",
    "PositionSize": "Half"
    },
    {
    "Symbol": "NVDA",
    "CompanyName": "Nvidia",
    "Price": 429.97,
    "PriceChange": 19.75,
    "PricePercentChange": 4.81,
    "Volume": 72031000,
    "VolumePercentChange": 51.71,
    "IsIndex": null,
    "Header": "Leaders",
    "Sector": null,
    "SectorRank": 0,
    "SymbolOrder": 0,
    "Story": "Nvidia has long&nbsp;served as&nbsp;a leader in computer graphics processors (GPUs) used in video games and other applications, but it is also making inroads in the virtualization, data center, AI, supercomputing&nbsp;and automotive markets. Analysts express hope that Nvidia will play a key role in powering the metaverse. Nvidia popped after Q4 earnings beat views and the chip giant guided slightly higher on Q1 revenue. Comments by CEO Jensen Huang on how its products will help power generative AI were met with enthusiasm. On Feb. 28, Nvidia announced plans to raise $10 billion \r\nfrom a variety of securities, based on a shelf registration filing to \r\nthe SEC. On March 21 it unveiled a range of initiatives at the GTC 2023 conference to broaden its reach in artificial intelligence. Fiscal Q1 earnings fell 20% to $1.09 a share. Revenue came in at $7.19 billion, well ahead of the $6.5 billion consensus. Nvidia significantly raised its revenue guidance for Q2 to $11 billion, plus or minus 2%, well above the $7.15 billion consensus. As a result, Wall Street's view has changed dramatically. Analysts on consensus now see earnings vaulting 108% in the current fiscal year ending in January 2024 to $6.95 a share and blasting 39% higher in FY 2025.<br>",
    "UpdateDate": "6/14/2023 10:25 AM",
    "NearBuyPoint": false,
    "BuyPoint": "230.49",
    "BuyRangeFrom": "230.49",
    "BuyRangeTo": "242.01",
    "CurrentAction": "Nvidia has cleared a 3-weeks tight entry near 405, a follow-on buy point. It rocketed after reporting blowout earnings on May 24. Headed into the report, NVDA was well clear of its 21-day exponential moving average after a strong rally and is comfortably above the benchmark. The chip giant joined Leaderboard after gapping up on earnings on Feb. 22. ",
    "LeaderboardAnalysis": "After a painful drawdown in 2022, NVDA has been fighting back valiantly. Institutional investors have been piling in, fueling its rise. The Accumulation/Distribution Rating recently stood at a strong A.",
    "BackStory": "Nvidia has long&nbsp;served as&nbsp;a leader in computer graphics processors (GPUs) used in video games and other applications, but it is also making inroads in the virtualization, data center, AI, supercomputing&nbsp;and automotive markets. Analysts express hope that Nvidia will play a key role in powering the metaverse. Nvidia popped after Q4 earnings beat views and the chip giant guided slightly higher on Q1 revenue. Comments by CEO Jensen Huang on how its products will help power generative AI were met with enthusiasm. On Feb. 28, Nvidia announced plans to raise $10 billion \r\nfrom a variety of securities, based on a shelf registration filing to \r\nthe SEC. On March 21 it unveiled a range of initiatives at the GTC 2023 conference to broaden its reach in artificial intelligence. Fiscal Q1 earnings fell 20% to $1.09 a share. Revenue came in at $7.19 billion, well ahead of the $6.5 billion consensus. Nvidia significantly raised its revenue guidance for Q2 to $11 billion, plus or minus 2%, well above the $7.15 billion consensus. As a result, Wall Street's view has changed dramatically. Analysts on consensus now see earnings vaulting 108% in the current fiscal year ending in January 2024 to $6.95 a share and blasting 39% higher in FY 2025.<br>",
    "IsInLeaderboard": true,
    "RecentArticle": "<div><a href=\"https://www.investors.com/news/technology/nvda-stock-nvidia-smashes-estimates-on-strong-data-center-sales/\" target=\"_blank\">AI Chipmaker Nvidia Smashes Quarterly Estimates On Strong Data-Center Sales</a><br></div><div><a href=\"https://www.investors.com/news/technology/nvidia-stock-chatgpt-is-just-the-start-for-artificial-intelligence/\" target=\"_blank\">Nvidia Ramps Up Artificial Intelligence Offerings</a><br></div><div><a href=\"https://www.investors.com/news/technology/nvda-stock-nvidia-delivers-upbeat-q4-report/\">Nvidia Beats Thanks To Data Center Growth, AI</a><br></div><div><a href=\"https://www.investors.com/news/technology/nvidia-stock-rises-above-key-technical-level/\" target=\"_blank\">Nvidia's Metaverse Play Is All Business</a><br></div><a href=\"https://www.investors.com/news/technology/semiconductor-stocks-called-the-new-oil-of-the-economy/\" target=\"_blank\">The 'New Oil' Of The Economy</a><br><br>",
    "PreviousClose": 410.22,
    "CheckupUrl": "https://research.investors.com/stock-checkup/nasdaq-nvidia-nvda.aspx",
    "LatestQtrEpsPerChg": null,
    "PriorQtrEpsPerChg": null,
    "CurQtrSalesPerChg": null,
    "CurYrEpsEstPerChg": null,
    "CompRating": null,
    "EPSRating": null,
    "RSRating": null,
    "SmrRating": null,
    "AccDisRating": null,
    "GrpStr": null,
    "ListName": "Leaders",
    "PositionSize": "Quarter"
    },
    {
    "Symbol": "PANW",
    "CompanyName": "Palo Alto Networks",
    "Price": 238.56,
    "PriceChange": 4.93,
    "PricePercentChange": 2.11,
    "Volume": 5551000,
    "VolumePercentChange": 22.68,
    "IsIndex": null,
    "Header": "Leaders",
    "Sector": null,
    "SectorRank": 0,
    "SymbolOrder": 0,
    "Story": "The stock was given a boost <strong></strong>after the cybersecurity firm's fiscal third-quarter earnings and revenue topped analyst targets. In addition, billings, a sales growth metric, rose 26% to $2.3 billion, edging by estimates of $2.228 billion. William Blair analyst Jonathan Ho noted significant growth in large-deal activity deals of more than $10 million growing 136% over the prior-year quarter. Wall Street envisions profits rising 42% in the fiscal year ending in July 2023 to $3.58 a share, then up 22% in FY 2024. Palo Alto holds zero long-term debt. The stock is to become a member of the S&amp;P 500 on June 20. <br>",
    "UpdateDate": "6/13/2023 5:35 PM",
    "NearBuyPoint": false,
    "BuyPoint": "203.44",
    "BuyRangeFrom": "203.44",
    "BuyRangeTo": "213.61",
    "CurrentAction": "Palo Alto Networks popped last week on the news it will be joining the S&amp;P 500. It joined as a new position after it surged on earnings and is now above a buy zone from a conventional entry. The relative strength line is hitting fresh heights, a bullish sign. ",
    "LeaderboardAnalysis": "Breakout attempts in both 2021 and 2022 failed. So the stock has had a long time to digest its multiyear gains. Palo Alto has made a big move off the January lows and is up around 50% so far in 2023.<br>",
    "BackStory": "The stock was given a boost <strong></strong>after the cybersecurity firm's fiscal third-quarter earnings and revenue topped analyst targets. In addition, billings, a sales growth metric, rose 26% to $2.3 billion, edging by estimates of $2.228 billion. William Blair analyst Jonathan Ho noted significant growth in large-deal activity deals of more than $10 million growing 136% over the prior-year quarter. Wall Street envisions profits rising 42% in the fiscal year ending in July 2023 to $3.58 a share, then up 22% in FY 2024. Palo Alto holds zero long-term debt. The stock is to become a member of the S&amp;P 500 on June 20. <br>",
    "IsInLeaderboard": true,
    "RecentArticle": "<p><a href=\"https://www.investors.com/news/technology/panw-stock-palo-alto-earnings-q12023/\" target=\"_blank\">Palo Alto Tops Estimates On Cloud, Large Customer Growth<br></a><a href=\"https://www.investors.com/news/technology/panw-stock-palo-alto-earnings-q42022/\" target=\"_blank\">Cloud Growth Boosts Palo Alto Q2 Earnings</a><br><a href=\"https://www.investors.com/news/technology/panw-stock-palo-alto-earnings-palo-alto-stock-q22022/\" target=\"_blank\">Palo Alto Earnings, Guidance Top Views</a></p>",
    "PreviousClose": 233.63,
    "CheckupUrl": "https://research.investors.com/stock-checkup/nasdaq-palo-alto-networks-panw.aspx",
    "LatestQtrEpsPerChg": null,
    "PriorQtrEpsPerChg": null,
    "CurQtrSalesPerChg": null,
    "CurYrEpsEstPerChg": null,
    "CompRating": null,
    "EPSRating": null,
    "RSRating": null,
    "SmrRating": null,
    "AccDisRating": null,
    "GrpStr": null,
    "ListName": "Leaders",
    "PositionSize": "Half"
    },
    {
    "Symbol": "RCL",
    "CompanyName": "Royal Caribbean Group",
    "Price": 94.72,
    "PriceChange": -1.08,
    "PricePercentChange": -1.13,
    "Volume": 3852000,
    "VolumePercentChange": 4.56,
    "IsIndex": null,
    "Header": "Leaders",
    "Sector": null,
    "SectorRank": 0,
    "SymbolOrder": 0,
    "Story": "Royal Caribbean Cruises is the world’s second-largest cruise ship company. The stock was badly hit amid the coronovirus pandemic. But results have been steadily improving amid easy year-over-year comparisons. Analysts see the firm going from a loss of $7.50 per share in 2022 to an upwardly revised earnings of $4.72 per share in 2023. A further gain of 48% is seen in 2024. Funds have been piling in of late, lifting its Accumulation/Distribution Rating to A+, the highest possible.<br>",
    "UpdateDate": "6/14/2023 10:29 AM",
    "NearBuyPoint": false,
    "BuyPoint": "78.38",
    "BuyRangeFrom": "78.38",
    "BuyRangeTo": "82.30",
    "CurrentAction": "Royal Caribbean retook a handle entry and has carried on cruising higher. It previously broke out on earnings. The stock recently delivered a 20% profit from the cup's 76.30 buy point and has just touched this level from the 78.38 entry. Numerous spikes in volume on RCL's up days have sent the up/down volume ratio to an incredible level of 2.7; 1.0 is considered a neutral level of volume between up days and down days in price. ",
    "LeaderboardAnalysis": "This is a first-stage cup base for the turnaround play. The firm is looking to return to significant profitability this year; Wall Street thinks RCL can earn $4.72 a share. That would be the brightest result since the company earned $9.54 a share in 2019. Volume was high on the breakout while the pullback has been in light volume, an encouraging sign.<br>",
    "BackStory": "Royal Caribbean Cruises is the world’s second-largest cruise ship company. The stock was badly hit amid the coronovirus pandemic. But results have been steadily improving amid easy year-over-year comparisons. Analysts see the firm going from a loss of $7.50 per share in 2022 to an upwardly revised earnings of $4.72 per share in 2023. A further gain of 48% is seen in 2024. Funds have been piling in of late, lifting its Accumulation/Distribution Rating to A+, the highest possible.<br>",
    "IsInLeaderboard": true,
    "RecentArticle": "<a href=\"https://www.investors.com/stock-lists/ibd-50/these-travel-stocks-are-flying-higher-uber-stock-is-cruising-on-up/\" target=\"_blank\">Inside IBD 50: These Travel Stocks Fly Higher</a>",
    "PreviousClose": 95.8,
    "CheckupUrl": "https://research.investors.com/stock-checkup/nyse-royal-caribbean-group-rcl.aspx",
    "LatestQtrEpsPerChg": null,
    "PriorQtrEpsPerChg": null,
    "CurQtrSalesPerChg": null,
    "CurYrEpsEstPerChg": null,
    "CompRating": null,
    "EPSRating": null,
    "RSRating": null,
    "SmrRating": null,
    "AccDisRating": null,
    "GrpStr": null,
    "ListName": "Leaders",
    "PositionSize": "Half"
    },
    {
    "Symbol": "CRM",
    "CompanyName": "Salesforce",
    "Price": 209.4,
    "PriceChange": 0.42,
    "PricePercentChange": 0.2,
    "Volume": 8846000,
    "VolumePercentChange": 38.84,
    "IsIndex": null,
    "Header": "Leaders",
    "Sector": null,
    "SectorRank": 0,
    "SymbolOrder": 0,
    "Story": "Salesforce.com is a pioneer in customer management software. It was boosted after Q4 earnings topped views while revenue guidance also came in above expectations. It also announced it has disbanded a panel that explores mergers and acquisitions, implying it will make no more big acquisitions, amid growing pressure from activist investors. Fiscal Q1 profit jumped 72% to $1.69 a share, with revenue up 11% to $8.25 billion. Wall Street has boosted profit views recently; it sees EPS rising 24% to $6.51 in fiscal 2024 and popping a further 19% in fiscal 2025.<br>",
    "UpdateDate": "6/14/2023 10:41 AM",
    "NearBuyPoint": false,
    "BuyPoint": "193.91",
    "BuyRangeFrom": "193.91",
    "BuyRangeTo": "203.61",
    "CurrentAction": "Salesforce managed to steady itself after slumping following earnings. It is now testing support at the 21-day exponential moving average. The megacap tech previously moved past a pair of new alternative entries at 194.01 and at 200.10. It previously passed a prior 178.84 handle buy point and has delivered a 25% profit from that entry. Back in March, the 50-day moving average mounted the 200-day line, a bullish sign. ",
    "LeaderboardAnalysis": "It has formed a new handle after attempting to break out from a first-stage cup-with-handle entry. This was a bottoming base. The Dow Jones Industrial Average stock has made impressive progress following a blockbuster earnings report.<br>",
    "BackStory": "Salesforce.com is a pioneer in customer management software. It was boosted after Q4 earnings topped views while revenue guidance also came in above expectations. It also announced it has disbanded a panel that explores mergers and acquisitions, implying it will make no more big acquisitions, amid growing pressure from activist investors. Fiscal Q1 profit jumped 72% to $1.69 a share, with revenue up 11% to $8.25 billion. Wall Street has boosted profit views recently; it sees EPS rising 24% to $6.51 in fiscal 2024 and popping a further 19% in fiscal 2025.<br>",
    "IsInLeaderboard": true,
    "RecentArticle": "<p><a href=\"https://www.investors.com/news/technology/crm-stock-salesforce-stock-salesforce-earnings-q12023/\" target=\"_blank\">Salesforce Delivers On Margin Improvement But Sales Outlook Only Edges By Views</a><br></p>",
    "PreviousClose": 208.98,
    "CheckupUrl": "https://research.investors.com/stock-checkup/nyse-salesforce-crm.aspx",
    "LatestQtrEpsPerChg": null,
    "PriorQtrEpsPerChg": null,
    "CurQtrSalesPerChg": null,
    "CurYrEpsEstPerChg": null,
    "CompRating": null,
    "EPSRating": null,
    "RSRating": null,
    "SmrRating": null,
    "AccDisRating": null,
    "GrpStr": null,
    "ListName": "Leaders",
    "PositionSize": "Half"
    },
    {
    "Symbol": "SHOP",
    "CompanyName": "Shopify Cl A",
    "Price": 65.88,
    "PriceChange": 2.04,
    "PricePercentChange": 3.2,
    "Volume": 16620000,
    "VolumePercentChange": -0.3,
    "IsIndex": null,
    "Header": "Leaders",
    "Sector": null,
    "SectorRank": 0,
    "SymbolOrder": 0,
    "Story": "The company sets up e-commerce websites for small businesses, and partners with others to handle digital payments and shipping. The stock has strong IBD scores, including a 98 Composite Rating and a Relative Strength Rating of 97. Shopify's earnings plunged to 4 cents a share last year but are seen vaulting to 33 cents this year and 55 cents in 2024. <br>",
    "UpdateDate": "6/14/2023 5:11 PM",
    "NearBuyPoint": false,
    "BuyPoint": "61.49",
    "BuyRangeFrom": "61.49",
    "BuyRangeTo": "64.56",
    "CurrentAction": "Shopify rejoined the Leaders after it cleared a trendline. It is now clear of its 10-day line after a test. SHOP made nice progress after gapping up above a buy point of 49.86 from a cup with handle in early May; it is extended from this initial entry. ",
    "LeaderboardAnalysis": "The handle was formed in light volume. The depth of 29% in the cup and 8% in the handle were near-ideal.\r\nShopify saw sales grow for the seventh quarter in a row to $1.5 billion though earnings declined.",
    "BackStory": "The company sets up e-commerce websites for small businesses, and partners with others to handle digital payments and shipping. The stock has strong IBD scores, including a 98 Composite Rating and a Relative Strength Rating of 97. Shopify's earnings plunged to 4 cents a share last year but are seen vaulting to 33 cents this year and 55 cents in 2024. <br>",
    "IsInLeaderboard": true,
    "RecentArticle": "<p><a href=\"https://www.investors.com/news/technology/shop-stock-surges-shopify-earnings-sells-logistics-business/\">Shopify Surprises With Earnings, SHOP Stock Surges</a><br></p>",
    "PreviousClose": 63.84,
    "CheckupUrl": "https://research.investors.com/stock-checkup/nyse-shopify-cl-a-shop.aspx",
    "LatestQtrEpsPerChg": null,
    "PriorQtrEpsPerChg": null,
    "CurQtrSalesPerChg": null,
    "CurYrEpsEstPerChg": null,
    "CompRating": null,
    "EPSRating": null,
    "RSRating": null,
    "SmrRating": null,
    "AccDisRating": null,
    "GrpStr": null,
    "ListName": "Leaders",
    "PositionSize": "Half"
    },
    {
    "Symbol": "TSLA",
    "CompanyName": "Tesla",
    "Price": 256.79,
    "PriceChange": -1.92,
    "PricePercentChange": -0.74,
    "Volume": 167857000,
    "VolumePercentChange": 25.96,
    "IsIndex": null,
    "Header": "Leaders",
    "Sector": null,
    "SectorRank": 0,
    "SymbolOrder": 0,
    "Story": "Tesla&nbsp;has moved its corporate&nbsp;HQ to Austin, Texas, where its gigafactory now produces Model Y vehicles. The company has established itself as the leader in the still young EV market. Wall Street expects the company, which is also active in battery storage and is developing an AI robotics business, to recover from an estimated 17% drop in full-year earnings with 43% growth in 2024 to $4.82 a share.<br>",
    "UpdateDate": "6/14/2023 5:12 PM",
    "NearBuyPoint": false,
    "BuyPoint": "207.79",
    "BuyRangeFrom": "207.79",
    "BuyRangeTo": "218.18",
    "CurrentAction": "Tesla joined the Leaders as it cleared a double-bottom base and has quickly passed the 20% profit target. The stock recently cleared a trendline drawn from the February peak. Punching through the 200-day moving average was a key move. The relative strength line is spiking sharply upwards as it moves sharply off recent lows. ",
    "LeaderboardAnalysis": "This is a first-stage base for Tesla. Such early-stage patterns are more likely to net strong gains for investors. TSLA has been in mighty form so far in 2023, rising almost 100%. Overall fund owenership remains relatively low however, coming in at 33%.",
    "BackStory": "Tesla&nbsp;has moved its corporate&nbsp;HQ to Austin, Texas, where its gigafactory now produces Model Y vehicles. The company has established itself as the leader in the still young EV market. Wall Street expects the company, which is also active in battery storage and is developing an AI robotics business, to recover from an estimated 17% drop in full-year earnings with 43% growth in 2024 to $4.82 a share.<br>",
    "IsInLeaderboard": true,
    "RecentArticle": "<p><a href=\"https://www.investors.com/news/tesla-quietly-increases-u-s-vehicle-discounts-elon-musk-doesnt-unveil-new-model-3/\" target=\"_blank\">Tesla Quietly Increases U.S. EV Discounts</a></p><p><a href=\"https://www.investors.com/news/is-tesla-stock-a-buy-or-a-sell-right-now-as-elon-musk-teases-cybertruck/\" target=\"_blank\">Is Tesla Stock A Buy Or A Sell Now?</a><br></p>",
    "PreviousClose": 258.71,
    "CheckupUrl": "https://research.investors.com/stock-checkup/nasdaq-tesla-tsla.aspx",
    "LatestQtrEpsPerChg": null,
    "PriorQtrEpsPerChg": null,
    "CurQtrSalesPerChg": null,
    "CurYrEpsEstPerChg": null,
    "CompRating": null,
    "EPSRating": null,
    "RSRating": null,
    "SmrRating": null,
    "AccDisRating": null,
    "GrpStr": null,
    "ListName": "Leaders",
    "PositionSize": "Half"
    },
    {
    "Symbol": "UBER",
    "CompanyName": "Uber Technologies",
    "Price": 41.27,
    "PriceChange": -0.14,
    "PricePercentChange": -0.34,
    "Volume": 14872000,
    "VolumePercentChange": -37.59,
    "IsIndex": null,
    "Header": "Leaders",
    "Sector": null,
    "SectorRank": 0,
    "SymbolOrder": 0,
    "Story": "The stock has taken buy-and-hold investors on a long, tough journey of ups and downs since going public in 2019. The app-based taxi and food delivery service is still not consistently profitable on an annual basis. Uber posted a profit of 59 cents a share in 2018, but then lost $5.04 a share and $3.86 a share the next two years. On Feb. 8, the ride-hailing giant reported fourth-quarter earnings of 29 cents a share, down 34% vs. a year earlier, on a 49% climb in revenue to $8.6 billion. Analysts expected Uber to report a loss of 15 cents on revenue of $8.5 billion. Bloomberg reported March 8 that the company is considering spinning off or selling its freight logistics business. For Q1 the firm posted a loss of 8 cents per share, better than views for a loss of 9 cents per share. This compares to a loss of $3.03 a year a earlier. A 29% revenue pop to $8.82 billion also topped expectations. Uber guided for gross bookings between $33 billion to $34 billion and an adjusted EBITDA of $800 million to $850 million for Q2.<br>",
    "UpdateDate": "6/14/2023 5:12 PM",
    "NearBuyPoint": false,
    "BuyPoint": "37.58",
    "BuyRangeFrom": "37.58",
    "BuyRangeTo": "39.46",
    "CurrentAction": "Uber vaulted away from a trendline entry near 32 after posting better than expected results on May 2. It was then raised by a further quarter after clearing a mini-trendline. It is extended from a conventional entry now. ",
    "LeaderboardAnalysis": "At the time of the call option purchase, the current midpoint of the 33 call option expiring on May 12 stood at $1.48, or equal to roughly 4.7% of the total cost of the stock on a per-share basis. A monthly chart shows the stock is still trading more than 40% below its all-time peak.<br>",
    "BackStory": "The stock has taken buy-and-hold investors on a long, tough journey of ups and downs since going public in 2019. The app-based taxi and food delivery service is still not consistently profitable on an annual basis. Uber posted a profit of 59 cents a share in 2018, but then lost $5.04 a share and $3.86 a share the next two years. On Feb. 8, the ride-hailing giant reported fourth-quarter earnings of 29 cents a share, down 34% vs. a year earlier, on a 49% climb in revenue to $8.6 billion. Analysts expected Uber to report a loss of 15 cents on revenue of $8.5 billion. Bloomberg reported March 8 that the company is considering spinning off or selling its freight logistics business. For Q1 the firm posted a loss of 8 cents per share, better than views for a loss of 9 cents per share. This compares to a loss of $3.03 a year a earlier. A 29% revenue pop to $8.82 billion also topped expectations. Uber guided for gross bookings between $33 billion to $34 billion and an adjusted EBITDA of $800 million to $850 million for Q2.<br>",
    "IsInLeaderboard": true,
    "RecentArticle": "<p><a href=\"https://www.investors.com/news/technology/uber-stock-jumps-on-quarterly-earnings-beat/\" target=\"_blank\">Uber Turns An Expected Loss Into A Gain</a><br><a href=\"https://www.barrons.com/articles/uber-stock-price-director-purchase-51675260157?mod=bar_ibd_news\" target=\"_blank\">Barron's: Uber Director Makes Large Share Buy</a></p>",
    "PreviousClose": 41.41,
    "CheckupUrl": "https://research.investors.com/stock-checkup/nyse-uber-technologies-uber.aspx",
    "LatestQtrEpsPerChg": null,
    "PriorQtrEpsPerChg": null,
    "CurQtrSalesPerChg": null,
    "CurYrEpsEstPerChg": null,
    "CompRating": null,
    "EPSRating": null,
    "RSRating": null,
    "SmrRating": null,
    "AccDisRating": null,
    "GrpStr": null,
    "ListName": "Leaders",
    "PositionSize": "Three Quarters"
    },
    {
    "Symbol": "UAL",
    "CompanyName": "United Airlines",
    "Price": 53.35,
    "PriceChange": 0.16,
    "PricePercentChange": 0.3,
    "Volume": 6498000,
    "VolumePercentChange": -9.01,
    "IsIndex": null,
    "Header": "Watchlist",
    "Sector": null,
    "SectorRank": 0,
    "SymbolOrder": 0,
    "Story": "Make no mistake: UAL is an earnings turnaround story. The airline giant is coming out of a long slump due to the coronovirus pandemic. The stock returned to profitability in 2022, earning $2.52 a share. Now, analysts expect full-year EPS in 2023 to rocket 269% to $9.29. Mutual fund sponsors have grown from 728 at the end of 2021 to as many as 978 at the end of Q1 this year.<br>",
    "UpdateDate": "6/14/2023 10:07 AM",
    "NearBuyPoint": true,
    "BuyPoint": "55.04",
    "BuyRangeFrom": "55.04",
    "BuyRangeTo": "57.79",
    "CurrentAction": "United Airlines has formed a new first-stage base. The RS line is rising but not quite near its peak since the latest consolidation began in March.<br>",
    "LeaderboardAnalysis": "UAL is going for its sixth weekly gain in seven weeks. That indicates demand among the institutional crowd is strengthening. A flat-base breakout at 53.26 failed quickly. The steep sell-off did not change the fact that the stock is still in a long-winded first-stage basing cycle.<br>",
    "BackStory": "Make no mistake: UAL is an earnings turnaround story. The airline giant is coming out of a long slump due to the coronovirus pandemic. The stock returned to profitability in 2022, earning $2.52 a share. Now, analysts expect full-year EPS in 2023 to rocket 269% to $9.29. Mutual fund sponsors have grown from 728 at the end of 2021 to as many as 978 at the end of Q1 this year.<br>",
    "IsInLeaderboard": true,
    "RecentArticle": "<a href=\"https://www.investors.com/research/google-stock-best-stocks-to-buy-and-watch-chipotle-delta-air-lines-united-airlines/\" target=\"_blank\">IBD Screen Of The Day</a><br><a href=\"https://www.investors.com/news/boeing-stock-takes-off-on-united-airlines-deal-buzz/\" target=\"_blank\">Boeing Stock Takes Off On United Airlines Deal Buzz</a><br><a href=\"https://www.investors.com/research/united-airlines-stock-buy-now/\" target=\"_blank\">Is United Airlines Stock A Buy Right Now?</a>",
    "PreviousClose": 53.19,
    "CheckupUrl": "https://research.investors.com/stock-checkup/nasdaq-united-airlines-ual.aspx",
    "LatestQtrEpsPerChg": null,
    "PriorQtrEpsPerChg": null,
    "CurQtrSalesPerChg": null,
    "CurYrEpsEstPerChg": null,
    "CompRating": null,
    "EPSRating": null,
    "RSRating": null,
    "SmrRating": null,
    "AccDisRating": null,
    "GrpStr": null,
    "ListName": "Watchlist",
    "PositionSize": ""
    },
    {
    "Symbol": "CMG",
    "CompanyName": "Chipotle Mexican Grill",
    "Price": 2061.17,
    "PriceChange": -4.56,
    "PricePercentChange": -0.22,
    "Volume": 119000,
    "VolumePercentChange": -60.33,
    "IsIndex": null,
    "Header": "Watchlist",
    "Sector": null,
    "SectorRank": 0,
    "SymbolOrder": 0,
    "Story": "With a new CEO in charge since March 2018, the Mexican food giant is turning itself around after a string of food safety incidents damaged the brand. Chipotle's&nbsp;successful digital strategy makes it easier for customers to order on devices,  improve the processing of orders and serve more customers. Q1 profit surged 84% to $10.50 a share, with revenue up 17% to $2.37 billion. Bottom-line and top-line growth accelerated from Q4. Wall Street predicts earnings to grow 35% this year to $44.35 a share and up 21% to $53.46 in 2024.<br>",
    "UpdateDate": "6/13/2023 5:31 PM",
    "NearBuyPoint": false,
    "BuyPoint": "1,724.71",
    "BuyRangeFrom": "1,724.71",
    "BuyRangeTo": "1,810.95",
    "CurrentAction": "Chipotle Mexican Grill is holding gains well after gapping up on earnings. Tight trading lately may result in a new base near 2,077 or 2,139 and a follow-on entry point. CMG previously hit the 20% profit goal from its latest entry.<br>",
    "LeaderboardAnalysis": "The earnings gap came after Chipotle cleared a shallow cup base in early April. All of the key moving averages are rising steadily, a good technical sign. Since March, volume on the upside has mostly dwarfed turnover during price drops. As of June 3, the up/down volume ratio was at a ridiculously bullish level of 2.4.<br>",
    "BackStory": "With a new CEO in charge since March 2018, the Mexican food giant is turning itself around after a string of food safety incidents damaged the brand. Chipotle's&nbsp;successful digital strategy makes it easier for customers to order on devices,  improve the processing of orders and serve more customers. Q1 profit surged 84% to $10.50 a share, with revenue up 17% to $2.37 billion. Bottom-line and top-line growth accelerated from Q4. Wall Street predicts earnings to grow 35% this year to $44.35 a share and up 21% to $53.46 in 2024.<br>",
    "IsInLeaderboard": true,
    "RecentArticle": "<p><a href=\"https://www.investors.com/news/mcdonalds-stock-chipotle-peg-new-highs-ahead-of-tuesday-reports/\" target=\"_blank\">Chipotle Rockets To All-Time Highs</a></p>",
    "PreviousClose": 2065.73,
    "CheckupUrl": "https://research.investors.com/stock-checkup/nyse-chipotle-mexican-grill-cmg.aspx",
    "LatestQtrEpsPerChg": null,
    "PriorQtrEpsPerChg": null,
    "CurQtrSalesPerChg": null,
    "CurYrEpsEstPerChg": null,
    "CompRating": null,
    "EPSRating": null,
    "RSRating": null,
    "SmrRating": null,
    "AccDisRating": null,
    "GrpStr": null,
    "ListName": "Watchlist",
    "PositionSize": ""
    },
    {
    "Symbol": "CHDN",
    "CompanyName": "Churchill Downs",
    "Price": 137.85,
    "PriceChange": -1.17,
    "PricePercentChange": -0.84,
    "Volume": 261000,
    "VolumePercentChange": -34.06,
    "IsIndex": null,
    "Header": "Watchlist",
    "Sector": "LEISURE",
    "SectorRank": 8,
    "SymbolOrder": 0,
    "Story": "CHDN is a racing, online wagering and gaming entertainment company. Earnings and revenue growth has accelerated for two straight quarters. On the top line, they've gone from a 3% dip in Q3 2022 to gains of 32% and 54% in Q4 and Q1 of this year, respectively. Q1 profit jumped 66%, with revenue up 54% to $559.5 million. Wall Street sees rosy profits ahead this year with a gain of 51% to $6.19 a share and a 22% boost in 2024. The 73% ROE logged in 2022 is distorted by a long-term debt to equity ratio of 827% the same year. The company suspended racing at its Churchill Downs Racetrack after a dozen horses died in the space of a month. The suspension will last for roughly one month.",
    "UpdateDate": "6/12/2023 4:17 PM",
    "NearBuyPoint": false,
    "BuyPoint": "150.45",
    "BuyRangeFrom": "150.45",
    "BuyRangeTo": "157.97",
    "CurrentAction": "Churchill Downs joins the Watchlist as it fights back from a recent selloff and forms a new flat base. Plus, a trendline buy point may emerge. An attempted rebound off the 50-day and 10-week moving averages briefly went awry on news it is suspending racing operations at its Churchill Downs Racetrack due to an unusual number of horse deaths. A two-for-one stock split took effect May 22. <br>",
    "LeaderboardAnalysis": "CHDN has been quite volatile after flashing a sell signal from an earlier entry of 253.39. But shares also found support near the rising 50-day line. A weekly chart illustrates the bullish crack through upside resistance near 260 going back to the first quarter of 2021.<br>",
    "BackStory": "CHDN is a racing, online wagering and gaming entertainment company. Earnings and revenue growth has accelerated for two straight quarters. On the top line, they've gone from a 3% dip in Q3 2022 to gains of 32% and 54% in Q4 and Q1 of this year, respectively. Q1 profit jumped 66%, with revenue up 54% to $559.5 million. Wall Street sees rosy profits ahead this year with a gain of 51% to $6.19 a share and a 22% boost in 2024. The 73% ROE logged in 2022 is distorted by a long-term debt to equity ratio of 827% the same year. The company suspended racing at its Churchill Downs Racetrack after a dozen horses died in the space of a month. The suspension will last for roughly one month.",
    "IsInLeaderboard": true,
    "RecentArticle": "<a href=\"https://www.investors.com/market-trend/stock-market-today/stock-market-rallies-on-newfound-banking-hopes-retail-stock-soars/\" target=\"_blank\">Stock Market Today: Churchill Stretches Past Buy Point</a><br>",
    "PreviousClose": 139.02,
    "CheckupUrl": "https://research.investors.com/stock-checkup/nasdaq-churchill-downs-chdn.aspx",
    "LatestQtrEpsPerChg": null,
    "PriorQtrEpsPerChg": null,
    "CurQtrSalesPerChg": null,
    "CurYrEpsEstPerChg": null,
    "CompRating": null,
    "EPSRating": null,
    "RSRating": null,
    "SmrRating": null,
    "AccDisRating": null,
    "GrpStr": null,
    "ListName": "Watchlist",
    "PositionSize": ""
    },
    {
    "Symbol": "ELF",
    "CompanyName": "E.L.F. Beauty",
    "Price": 101.93,
    "PriceChange": -0.58,
    "PricePercentChange": -0.57,
    "Volume": 788000,
    "VolumePercentChange": -20.99,
    "IsIndex": null,
    "Header": "Watchlist",
    "Sector": "CONSUMER",
    "SectorRank": 16,
    "SymbolOrder": 0,
    "Story": "The Oakland, Calif.-based company runs four brands: ELF Cosmetics, ELF Skin, Well People and Keys. Wall Street expects earnings to grow 9% to $1.81 a share in its current fiscal year 2024, with growth accelerating in 2025, up 16%. Institutional ownership has been rising, with as many as 549 funds owning the stock at the end of Q1. The company on May 24 delivered 42 cents in adjusted earnings per share and a 78% pop in revenue to $187.4 million. Gross margins rose on pricing, lower transport costs and favorable product mix. Management noted a 270-basis point gain in market share. ELF also forecast full-year sales of $705 mil-$720 mil, walloping the consensus view of $548 mil. The company forecast FY 2024 earnings at $1.73-$1.76 per share, well above the FactSet estimate at the time of $1.43.<br>",
    "UpdateDate": "6/13/2023 5:11 PM",
    "NearBuyPoint": false,
    "BuyPoint": "75.41",
    "BuyRangeFrom": "75.41",
    "BuyRangeTo": "79.18",
    "CurrentAction": "ELF shares jumped on a strong quarterly report and bullish full-year outlook, vaulting away from the 50-day line in the process. Like the stock itself, ELF's relative strength line surged into new high ground, but it's backed off highs in recent days.<br>",
    "LeaderboardAnalysis": "ELF's 21-day exponential moving average has risen to 100, a key psychological level. A further pullback by the stock could test both of these technical areas. ELF recently launched out of a third stage pattern, which increases risk of a sharper pullback. It has been on a real tear on 2023, reversing dramatically higher after flashing a sell signal from a second stage flat base in January. <br>",
    "BackStory": "The Oakland, Calif.-based company runs four brands: ELF Cosmetics, ELF Skin, Well People and Keys. Wall Street expects earnings to grow 9% to $1.81 a share in its current fiscal year 2024, with growth accelerating in 2025, up 16%. Institutional ownership has been rising, with as many as 549 funds owning the stock at the end of Q1. The company on May 24 delivered 42 cents in adjusted earnings per share and a 78% pop in revenue to $187.4 million. Gross margins rose on pricing, lower transport costs and favorable product mix. Management noted a 270-basis point gain in market share. ELF also forecast full-year sales of $705 mil-$720 mil, walloping the consensus view of $548 mil. The company forecast FY 2024 earnings at $1.73-$1.76 per share, well above the FactSet estimate at the time of $1.43.<br>",
    "IsInLeaderboard": true,
    "RecentArticle": "<a href=\"https://www.investors.com/research/the-new-america/elf-beauty-cruelty-free-makeup-and-teen-appeal-boost-sales/\" target=\"_blank\">ELF Beauty Soars On Cruelty-Free Cosmetics And Teen Appeal</a>",
    "PreviousClose": 102.51,
    "CheckupUrl": "https://research.investors.com/stock-checkup/nyse-elf-beauty-elf.aspx",
    "LatestQtrEpsPerChg": null,
    "PriorQtrEpsPerChg": null,
    "CurQtrSalesPerChg": null,
    "CurYrEpsEstPerChg": null,
    "CompRating": null,
    "EPSRating": null,
    "RSRating": null,
    "SmrRating": null,
    "AccDisRating": null,
    "GrpStr": null,
    "ListName": "Watchlist",
    "PositionSize": ""
    },
    {
    "Symbol": "ONON",
    "CompanyName": "On Holding",
    "Price": 29.85,
    "PriceChange": 0.11,
    "PricePercentChange": 0.37,
    "Volume": 5808000,
    "VolumePercentChange": 18.14,
    "IsIndex": null,
    "Header": "Watchlist",
    "Sector": null,
    "SectorRank": 0,
    "SymbolOrder": 0,
    "Story": "The Swiss running-shoe company caused a lot of early buzz by signing a deal with retired tennis star Roger Federer, who helped the firm launch eco-friendly sneakers made from vegan leather. Fidelity Contrafund, which initiated a stake in the company in 2021, doubled the size of its position in Q2 of last year. At the end of the first quarter this year, the mutual fund trimmed the stake by 60,000 shares to 8.22 million shares. Mutual funds owning shares have soared to 285 in Q1 2023 vs. 194 a year earlier. On May 16, the company reported earnings spiked 203% to 16 cents a share (according to MarketSmith) on an 80% boost in sales to $459 million, a quarterly record. It forecast full-year revenue of $1.95 billion, slightly above the $1.87 billion consensus. Tennis star Iga Swiatek, a newly signed celebrity endorser of the On brand, won the French Open's women's singles championship over the weekend.<br>",
    "UpdateDate": "6/12/2023 4:12 PM",
    "NearBuyPoint": false,
    "BuyPoint": "32.04",
    "BuyRangeFrom": "32.04",
    "BuyRangeTo": "33.64",
    "CurrentAction": "On joins the Watchlist as it bullishly reclaims its 50-day moving average. A base is clearly forming after the stock got gouged by sellers in May. The relative strength line is also moving higher after a recent dip.<br>",
    "LeaderboardAnalysis": "On dropped sharply after an attention-grabbing IPO. Overhead supply certainly remains. The latest handle showed a correction of 17%, on the deeper side. The cup's depth was also on the high side, at 38%. Prior to its catapult-like rise on March 21, short interest ran 8 times its average \r\ndaily volume at the time of 2.3 million shares. This equaled less than 3% of its \r\n636 million shares outstanding. Currently, short interest has been reduced to 3 times average daily volume.<br>",
    "BackStory": "The Swiss running-shoe company caused a lot of early buzz by signing a deal with retired tennis star Roger Federer, who helped the firm launch eco-friendly sneakers made from vegan leather. Fidelity Contrafund, which initiated a stake in the company in 2021, doubled the size of its position in Q2 of last year. At the end of the first quarter this year, the mutual fund trimmed the stake by 60,000 shares to 8.22 million shares. Mutual funds owning shares have soared to 285 in Q1 2023 vs. 194 a year earlier. On May 16, the company reported earnings spiked 203% to 16 cents a share (according to MarketSmith) on an 80% boost in sales to $459 million, a quarterly record. It forecast full-year revenue of $1.95 billion, slightly above the $1.87 billion consensus. Tennis star Iga Swiatek, a newly signed celebrity endorser of the On brand, won the French Open's women's singles championship over the weekend.<br>",
    "IsInLeaderboard": true,
    "RecentArticle": "<div><a href=\"https://www.investors.com/news/onon-stock-on-holding-earnings-q12023/\" target=\"_blank\">ONON Steps Back Despite Earnings Beat</a><br></div><div><a href=\"https://www.investors.com/research/ibd-stock-of-the-day/onon-stock-sets-up-as-options-play-with-on-holding-earnings-due/\" target=\"_blank\">IBD Stock Of The Day: ONON Stock Flashes Buy Signal On Earnings</a></div>\r\n<div><a href=\"https://www.investors.com/news/allbirds-stock-surges-debut-after-bird-ipo-prices-above-range/\" target=\"_blank\">On's Industry Mate Allbirds Makes Strong Market Debut</a></div>",
    "PreviousClose": 29.74,
    "CheckupUrl": "https://research.investors.com/stock-checkup/nyse-on-holding-onon.aspx",
    "LatestQtrEpsPerChg": null,
    "PriorQtrEpsPerChg": null,
    "CurQtrSalesPerChg": null,
    "CurYrEpsEstPerChg": null,
    "CompRating": null,
    "EPSRating": null,
    "RSRating": null,
    "SmrRating": null,
    "AccDisRating": null,
    "GrpStr": null,
    "ListName": "Watchlist",
    "PositionSize": ""
    },
    {
    "Symbol": "PEN",
    "CompanyName": "Penumbra",
    "Price": 337.53,
    "PriceChange": 5.81,
    "PricePercentChange": 1.75,
    "Volume": 507000,
    "VolumePercentChange": 44.08,
    "IsIndex": null,
    "Header": "Watchlist",
    "Sector": null,
    "SectorRank": 0,
    "SymbolOrder": 0,
    "Story": "The Alameda, Calif., firm develops devices to treat neurological and peripheral vascular-related disorders. It focuses on innovative techniques to remove blood clots with the help of computers and has a term for it: \"computer-orchestrated aspiration.\" In 2004, Penumbra launched its business to remove stroke-causing blood clots from the brain. Lord Abbett Developing Growth fund started a new position of 110,000 shares as of the first quarter this year. After a big drop in profits in 2022, from 70 cents a share in 2021 to 16 cents, it's expected to grow the bottom line by 881% this year to $1.57 a share. The forward-looking P-E ratio is an astounding 205X. Sales are likely headed to reach $1 billion on a trailing 12-month basis in the future. Analysts forecast sales, which have slowed to an 8% increase in the fourth quarter, to continue picking up from an 18% gain in the first quarter of this year to additional growth of 21% (to $253 million) and 25% (to $268 million) in Q2 and Q3, respectively.<br>",
    "UpdateDate": "6/12/2023 4:11 PM",
    "NearBuyPoint": true,
    "BuyPoint": "324.38",
    "BuyRangeFrom": "324.38",
    "BuyRangeTo": "340.60",
    "CurrentAction": "Penumbra has formed a narrow base, briefly testing the entry. Shares are clearing the entry again. Volume was light Monday ahead of the Federal Reserve's meeting on interest rates that begins Tuesday. The stock has made a dramatic recovery after bottoming out near 115 in June of 2022. At this point, a steeper pullback, a new test of the 10-week moving average, or further sideways action all seem possible.<br>",
    "LeaderboardAnalysis": "Penumbra showed a very early buy point at 201.53 after it formed a cup with handle within its incredibly deep cup pattern. No doubt: It has completed a bottoming pattern. Several new handle entries also formed along the way. Therefore, another big drop that sparks a new base is not impossible. However, the stock has received bullish buying support during normal-looking pullbacks to the 10-week line.<br>",
    "BackStory": "The Alameda, Calif., firm develops devices to treat neurological and peripheral vascular-related disorders. It focuses on innovative techniques to remove blood clots with the help of computers and has a term for it: \"computer-orchestrated aspiration.\" In 2004, Penumbra launched its business to remove stroke-causing blood clots from the brain. Lord Abbett Developing Growth fund started a new position of 110,000 shares as of the first quarter this year. After a big drop in profits in 2022, from 70 cents a share in 2021 to 16 cents, it's expected to grow the bottom line by 881% this year to $1.57 a share. The forward-looking P-E ratio is an astounding 205X. Sales are likely headed to reach $1 billion on a trailing 12-month basis in the future. Analysts forecast sales, which have slowed to an 8% increase in the fourth quarter, to continue picking up from an 18% gain in the first quarter of this year to additional growth of 21% (to $253 million) and 25% (to $268 million) in Q2 and Q3, respectively.<br>",
    "IsInLeaderboard": true,
    "RecentArticle": "<a href=\"https://www.investors.com/research/the-new-america/pen-stock-why-ceo-adam-elsesser-is-expecting-the-most-extraordinary-year/\" target=\"_blank\">The New America: CEO Says 2023 Will Be 'Most Extraordinary'</a><br>",
    "PreviousClose": 331.72,
    "CheckupUrl": "https://research.investors.com/stock-checkup/nyse-penumbra-pen.aspx",
    "LatestQtrEpsPerChg": null,
    "PriorQtrEpsPerChg": null,
    "CurQtrSalesPerChg": null,
    "CurYrEpsEstPerChg": null,
    "CompRating": null,
    "EPSRating": null,
    "RSRating": null,
    "SmrRating": null,
    "AccDisRating": null,
    "GrpStr": null,
    "ListName": "Watchlist",
    "PositionSize": ""
    },
    {
    "Symbol": "WING",
    "CompanyName": "Wingstop",
    "Price": 191.73,
    "PriceChange": 3.44,
    "PricePercentChange": 1.83,
    "Volume": 472000,
    "VolumePercentChange": -18.18,
    "IsIndex": null,
    "Header": "Watchlist",
    "Sector": null,
    "SectorRank": 0,
    "SymbolOrder": 0,
    "Story": "Fundamentals are solid at the restaurant chain as the company focuses on digital orders and delivery. Analysts have revised forecasts higher. They now see profits rising 15% to $2.12 a share in 2023 and up 16% in 2024. Recently, as much as 72% of the stock was held by funds. The up/down volume ratio has shown highly bullish levels, recently going as high as 1.8. This means volume has been up to 80% greater on up days vs. turnover on down days over the past 50 trading sessions. The firm posted earnings May 3, with EPS surging 79% to 59 cents on revenue of $109 million, up 43%. Both were better than analysts expected. The firm guided for high-single digit domestic same store sales growth in 2023.",
    "UpdateDate": "6/13/2023 5:25 PM",
    "NearBuyPoint": false,
    "BuyPoint": "193.74",
    "BuyRangeFrom": "193.74",
    "BuyRangeTo": "203.43",
    "CurrentAction": "Wingstop powered out of a buy zone after reporting strong earnings. But it has now undercut its buy point. WING is also losing ground on its 10-week moving average.<br>",
    "LeaderboardAnalysis": "The entire base formed above the 50-day line, a plus. Its relative strength line recently hit fresh heights. WING has more than tripled from its May 2022 low. However, the latest base continues a long-winding first-stage pattern for Wingstop. In a healthy uptrend, early-stage bases tend to result in rich gains for investors. The relative strength line has made new highs over the past month, an emblem of outperformance vs. the S&amp;P 500.<br>",
    "BackStory": "Fundamentals are solid at the restaurant chain as the company focuses on digital orders and delivery. Analysts have revised forecasts higher. They now see profits rising 15% to $2.12 a share in 2023 and up 16% in 2024. Recently, as much as 72% of the stock was held by funds. The up/down volume ratio has shown highly bullish levels, recently going as high as 1.8. This means volume has been up to 80% greater on up days vs. turnover on down days over the past 50 trading sessions. The firm posted earnings May 3, with EPS surging 79% to 59 cents on revenue of $109 million, up 43%. Both were better than analysts expected. The firm guided for high-single digit domestic same store sales growth in 2023.",
    "IsInLeaderboard": true,
    "RecentArticle": "<p><a href=\"https://www.investors.com/news/wingstop-stock-flies-out-of-base-after-tasty-earnings-beat/\" target=\"_blank\">Wingstop Flies Out Of Base After Tasty Earnings Beat</a><br></p>",
    "PreviousClose": 188.29,
    "CheckupUrl": "https://research.investors.com/stock-checkup/nasdaq-wingstop-wing.aspx",
    "LatestQtrEpsPerChg": null,
    "PriorQtrEpsPerChg": null,
    "CurQtrSalesPerChg": null,
    "CurYrEpsEstPerChg": null,
    "CompRating": null,
    "EPSRating": null,
    "RSRating": null,
    "SmrRating": null,
    "AccDisRating": null,
    "GrpStr": null,
    "ListName": "Watchlist",
    "PositionSize": ""
    }
    ]
};

export default data;